import { gql } from 'apollo-server-express';

export default gql`
  type Company {
    _id: ID!
    ticker: String,
    exchange: String,
    name: String,
    sector: String,
    industry: String,
    country: String,
    symbol: String!,
    Index: String,
    PE: Float,
    EPSttm: Float,
    InsiderOwn: Float,
    ShsOutstand: Float,
    PerfWeek: Float,
    MarketCap: Float,
    ForwardPE: Float,
    EPSnextY: Float,
    InsiderTrans: Float,
    ShsFloat: Float,
    PerfMonth: Float,
    Income: Float,
    PEG: Float,
    EPSnextQ: Float,
    InstOwn: Float,
    ShortFloat: Float,
    PerfQuarter: Float,
    Sales: Float,
    PS: Float,
    EPSthisY: Float,
    InstTrans: Float,
    ShortRatio: Float,
    PerfHalfY: Float,
    Booksh: Float,
    PB: Float,
    ROA: Float,
    TargetPrice: Float,
    PerfYear: Float,
    Cashsh: Float,
    PC: Float,
    EPSnext5Y: Float,
    ROE: Float,
    PerfYTD: Float,
    Dividend: Float,
    PFCF: Float,
    EPSpast5Y: Float,
    ROI: Float,
    Beta:Float,
    QuickRatio: Float,
    Salespast5Y: Float,
    GrossMargin: Float,
    ATR: Float,
    Employees: Float,
    CurrentRatio: Float,
    SalesQQ: Float,
    OperMargin: Float,
    RSI14: Float,
    Volatility: [Float],
    Optionable: Boolean,
    DebtEq: Float,
    EPSQQ: Float,
    ProfitMargin: Float,
    RelVolume: Float,
    PrevClose: Float,
    Shortable: Boolean,
    LTDebtEq: Float,
    Earnings: String,
    Payout: Float,
    AvgVolume: Float,
    Price: Float,
    Recom: Float,
    SMA20: Float,
    SMA50: Float,
    SMA200: Float,
    Volume: Float,
    Change: Float
  }
  type Range {
    min: Float,
    max: Float
  }
  type DistributionItem {
    name: Range,
    count: Int
  }
`;
